In [48]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import os
import warnings
warnings.filterwarnings('ignore')

In [49]:
car_data=pd.read_csv('audi.csv')
print(car_data)

      model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0        A1  2017  12500       Manual    15735   Petrol  150  55.4         1.4
1        A6  2016  16500    Automatic    36203   Diesel   20  64.2         2.0
2        A1  2016  11000       Manual    29946   Petrol   30  55.4         1.4
3        A4  2017  16800    Automatic    25952   Diesel  145  67.3         2.0
4        A3  2019  17300       Manual     1998   Petrol  145  49.6         1.0
...     ...   ...    ...          ...      ...      ...  ...   ...         ...
10663    A3  2020  16999       Manual     4018   Petrol  145  49.6         1.0
10664    A3  2020  16999       Manual     1978   Petrol  150  49.6         1.0
10665    A3  2020  17199       Manual      609   Petrol  150  49.6         1.0
10666    Q3  2017  19499    Automatic     8646   Petrol  150  47.9         1.4
10667    Q3  2016  15999       Manual    11855   Petrol  150  47.9         1.4

[10668 rows x 9 columns]


## Manual EDA

In [50]:
# Number of records
print(len(car_data))

10668


In [51]:
# Number of records- Shape
print(car_data.shape)

(10668, 9)


In [52]:
# Checking the datatype of each column
print(car_data.dtypes)

model            object
year              int64
price             int64
transmission     object
mileage           int64
fuelType         object
tax               int64
mpg             float64
engineSize      float64
dtype: object


In [53]:
# Checking null values
print(car_data.isna().sum())

model           0
year            0
price           0
transmission    0
mileage         0
fuelType        0
tax             0
mpg             0
engineSize      0
dtype: int64


In [54]:
# Dataset information
print(car_data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10668 entries, 0 to 10667
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   model         10668 non-null  object 
 1   year          10668 non-null  int64  
 2   price         10668 non-null  int64  
 3   transmission  10668 non-null  object 
 4   mileage       10668 non-null  int64  
 5   fuelType      10668 non-null  object 
 6   tax           10668 non-null  int64  
 7   mpg           10668 non-null  float64
 8   engineSize    10668 non-null  float64
dtypes: float64(2), int64(4), object(3)
memory usage: 750.2+ KB
None


In [55]:
# Dataset details of numeric columns
display(car_data.describe())

year          price        mileage           tax           mpg  \
count  10668.000000   10668.000000   10668.000000  10668.000000  10668.000000   
mean    2017.100675   22896.685039   24827.244001    126.011436     50.770022   
std        2.167494   11714.841888   23505.257205     67.170294     12.949782   
min     1997.000000    1490.000000       1.000000      0.000000     18.900000   
25%     2016.000000   15130.750000    5968.750000    125.000000     40.900000   
50%     2017.000000   20200.000000   19000.000000    145.000000     49.600000   
75%     2019.000000   27990.000000   36464.500000    145.000000     58.900000   
max     2020.000000  145000.000000  323000.000000    580.000000    188.300000   

         engineSize  
count  10668.000000  
mean       1.930709  
std        0.602957  
min        0.000000  
25%        1.500000  
50%        2.000000  
75%        2.000000  
max        6.300000

In [56]:
# Create x
x=car_data.iloc[:,[0,1,3,4,5,6,7,8]].values
print(x.shape)
print(x)

(10668, 8)
[[' A1' 2017 'Manual' ... 150 55.4 1.4]
 [' A6' 2016 'Automatic' ... 20 64.2 2.0]
 [' A1' 2016 'Manual' ... 30 55.4 1.4]
 ...
 [' A3' 2020 'Manual' ... 150 49.6 1.0]
 [' Q3' 2017 'Automatic' ... 150 47.9 1.4]
 [' Q3' 2016 'Manual' ... 150 47.9 1.4]]


In [57]:
# Create y
y=car_data.iloc[:,[2]].values
print(y.shape)
print(y)

(10668, 1)
[[12500]
 [16500]
 [11000]
 ...
 [17199]
 [19499]
 [15999]]


In [58]:
# Display Top 5 - X variable 
display(pd.DataFrame(x).head())

0     1          2      3       4    5     6    7
0   A1  2017     Manual  15735  Petrol  150  55.4  1.4
1   A6  2016  Automatic  36203  Diesel   20  64.2  2.0
2   A1  2016     Manual  29946  Petrol   30  55.4  1.4
3   A4  2017  Automatic  25952  Diesel  145  67.3  2.0
4   A3  2019     Manual   1998  Petrol  145  49.6  1.0

## Label Encoding To Columns- model and fuel type

In [59]:
from sklearn.preprocessing import LabelEncoder
l1=LabelEncoder()
x[:,0]=l1.fit_transform(x[:,0])
l2=LabelEncoder()
x[:,4]=l2.fit_transform(x[:,4])
display(pd.DataFrame(x))

0     1          2      3  4    5     6    7
0      0  2017     Manual  15735  2  150  55.4  1.4
1      5  2016  Automatic  36203  0   20  64.2  2.0
2      0  2016     Manual  29946  2   30  55.4  1.4
3      3  2017  Automatic  25952  0  145  67.3  2.0
4      2  2019     Manual   1998  2  145  49.6  1.0
...   ..   ...        ...    ... ..  ...   ...  ...
10663  2  2020     Manual   4018  2  145  49.6  1.0
10664  2  2020     Manual   1978  2  150  49.6  1.0
10665  2  2020     Manual    609  2  150  49.6  1.0
10666  9  2017  Automatic   8646  2  150  47.9  1.4
10667  9  2016     Manual  11855  2  150  47.9  1.4

[10668 rows x 8 columns]

## One Hot Encoding To Column- transmission


In [60]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(),[2])],remainder='passthrough')
x = ct.fit_transform(x)
display (x.shape)
display (pd.DataFrame(x))

(10668, 10)

0    1    2  3     4      5  6    7     8    9
0      0.0  1.0  0.0  0  2017  15735  2  150  55.4  1.4
1      1.0  0.0  0.0  5  2016  36203  0   20  64.2  2.0
2      0.0  1.0  0.0  0  2016  29946  2   30  55.4  1.4
3      1.0  0.0  0.0  3  2017  25952  0  145  67.3  2.0
4      0.0  1.0  0.0  2  2019   1998  2  145  49.6  1.0
...    ...  ...  ... ..   ...    ... ..  ...   ...  ...
10663  0.0  1.0  0.0  2  2020   4018  2  145  49.6  1.0
10664  0.0  1.0  0.0  2  2020   1978  2  150  49.6  1.0
10665  0.0  1.0  0.0  2  2020    609  2  150  49.6  1.0
10666  1.0  0.0  0.0  9  2017   8646  2  150  47.9  1.4
10667  0.0  1.0  0.0  9  2016  11855  2  150  47.9  1.4

[10668 rows x 10 columns]

## Features Scaling – Standardization 

In [61]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)
display(pd.DataFrame(x))

0         1         2         3         4         5         6  \
0     -0.583268  1.200728 -0.712333 -1.123544 -0.046450 -0.386836  1.050783   
1      1.714479 -0.832828 -0.712333 -0.160831 -0.507834  0.483989 -0.954181   
2     -0.583268  1.200728 -0.712333 -1.123544 -0.507834  0.217781  1.050783   
3      1.714479 -0.832828 -0.712333 -0.545916 -0.046450  0.047853 -0.954181   
4     -0.583268  1.200728 -0.712333 -0.738459  0.876318 -0.971285  1.050783   
...         ...       ...       ...       ...       ...       ...       ...   
10663 -0.583268  1.200728 -0.712333 -0.738459  1.337702 -0.885343  1.050783   
10664 -0.583268  1.200728 -0.712333 -0.738459  1.337702 -0.972136  1.050783   
10665 -0.583268  1.200728 -0.712333 -0.738459  1.337702 -1.030381  1.050783   
10666  1.714479 -0.832828 -0.712333  0.609339 -0.046450 -0.688442  1.050783   
10667 -0.583268  1.200728 -0.712333  0.609339 -0.507834 -0.551913  1.050783   

              7         8         9  
0      0.357147  0.357550 -0.880218  
1     -1.578323  1.037130  0.114925  
2     -1.429440  0.357550 -0.880218  
3      0.282706  1.276528  0.114925  
4      0.282706 -0.090355 -1.543647  
...         ...       ...       ...  
10663  0.282706 -0.090355 -1.543647  
10664  0.357147 -0.090355 -1.543647  
10665  0.357147 -0.090355 -1.543647  
10666  0.357147 -0.221637 -0.880218  
10667  0.357147 -0.221637 -0.880218  

[10668 rows x 10 columns]

## Train Test Split 

In [62]:
from sklearn.model_selection import train_test_split
(x_train,x_test,y_train,y_test)=train_test_split(x,y,test_size=0.2,random_state=0)
print(x.shape,y.shape)
print(x_train.shape,y_train.shape)
print(x_test.shape,y_test.shape)

(10668, 10) (10668, 1)
(8534, 10) (8534, 1)
(2134, 10) (2134, 1)


## Create Random Forest Regressor

In [63]:
from sklearn.ensemble import RandomForestRegressor
rf=RandomForestRegressor()
rf.fit(x_train,y_train)
display(rf)

RandomForestRegressor()

## Prediction with test data

In [64]:
y_pred=rf.predict(x_test)
display(y_pred)

array([14385.89, 23745.5 , 27500.51, ..., 46110.12, 31220.21, 10174.49])

## Display actual and Predicted Values 

In [65]:
print (pd.concat ([pd.DataFrame(y_test.reshape(len(y_test),1),columns =['Car Price']), 
                   pd.DataFrame(y_pred.reshape(len(y_pred),1),columns =['Price Prediction'])],axis =1))

      Car Price  Price Prediction
0         14998          14385.89
1         21950          23745.50
2         28990          27500.51
3         25489          27340.40
4         30950          32250.90
...         ...               ...
2129      23700          40060.83
2130      18000          16699.46
2131      45995          46110.12
2132      30500          31220.21
2133       8400          10174.49

[2134 rows x 2 columns]


## Display – Accuracy and Mean Absolute Error 

In [66]:
from sklearn.metrics import r2_score,mean_absolute_error
print('Accuracy: ',r2_score(y_test,y_pred))
print('Mean_Absolute_Error: ',mean_absolute_error(y_test,y_pred))

Accuracy:  0.9549077020003282
Mean_Absolute_Error:  1523.9082074217038


## Prediction with complete data

In [67]:
c_pred=rf.predict(x)
display(c_pred)

array([12789.3 , 16620.17, 11768.37, ..., 17574.47, 20339.79, 18481.96])

## Display actual and Predicted Values

In [68]:
display(pd.concat ([car_data,pd.DataFrame(c_pred.reshape(len(c_pred),1),columns =['Price Prediction'])],axis =1))

model  year  price transmission  mileage fuelType  tax   mpg  \
0        A1  2017  12500       Manual    15735   Petrol  150  55.4   
1        A6  2016  16500    Automatic    36203   Diesel   20  64.2   
2        A1  2016  11000       Manual    29946   Petrol   30  55.4   
3        A4  2017  16800    Automatic    25952   Diesel  145  67.3   
4        A3  2019  17300       Manual     1998   Petrol  145  49.6   
...     ...   ...    ...          ...      ...      ...  ...   ...   
10663    A3  2020  16999       Manual     4018   Petrol  145  49.6   
10664    A3  2020  16999       Manual     1978   Petrol  150  49.6   
10665    A3  2020  17199       Manual      609   Petrol  150  49.6   
10666    Q3  2017  19499    Automatic     8646   Petrol  150  47.9   
10667    Q3  2016  15999       Manual    11855   Petrol  150  47.9   

       engineSize  Price Prediction  
0             1.4          12789.30  
1             2.0          16620.17  
2             1.4          11768.37  
3             2.0          17646.41  
4             1.0          17254.83  
...           ...               ...  
10663         1.0          17001.39  
10664         1.0          17198.60  
10665         1.0          17574.47  
10666         1.4          20339.79  
10667         1.4          18481.96  

[10668 rows x 10 columns]

## Display – Accuracy and Mean Absolute Error

In [69]:
from sklearn.metrics import r2_score,mean_absolute_error
print('Accuracy: ',r2_score(y,c_pred))
print('Mean_Absolute_Error: ',mean_absolute_error(y,c_pred))

Accuracy:  0.9857427123869804
Mean_Absolute_Error:  782.5519665607719


## Create Linear Regression Model

In [70]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)
display(lr)

LinearRegression()

## Prediction with test data

In [71]:
y_pred=lr.predict(x_test)
display(pd.DataFrame(y_pred))

0
0     13062.417648
1     29350.247388
2     31943.967808
3     26795.619718
4     31438.948683
...            ...
2129  41582.338659
2130  20715.033809
2131  42611.259923
2132  31515.735002
2133   7294.332756

[2134 rows x 1 columns]

## Display Actual and Predicted Values

In [72]:
print (pd.concat ([pd.DataFrame(y_test.reshape(len(y_test),1),columns =['Car Price']), 
                   pd.DataFrame(y_pred.reshape(len(y_pred),1),columns =['Price Prediction'])],axis =1))

      Car Price  Price Prediction
0         14998      13062.417648
1         21950      29350.247388
2         28990      31943.967808
3         25489      26795.619718
4         30950      31438.948683
...         ...               ...
2129      23700      41582.338659
2130      18000      20715.033809
2131      45995      42611.259923
2132      30500      31515.735002
2133       8400       7294.332756

[2134 rows x 2 columns]


## Display- Accuracy and Mean Absolute Error

In [73]:
from sklearn.metrics import r2_score,mean_absolute_error
print('Accuracy: ',r2_score(y_test,y_pred))
print('Mean_Absolute_Error: ',mean_absolute_error(y_test,y_pred))

Accuracy:  0.7916670925031881
Mean_Absolute_Error:  3381.9167483000706


## Prediction for complete dataset

In [74]:
c_pred=lr.predict(x)
display(c_pred)

array([[14629.83482405],
       [20670.90779921],
       [13810.01031988],
       ...,
       [19407.66134549],
       [21034.83116012],
       [16691.09313906]])

## Display Actual and Predicted values

In [75]:
display(pd.concat ([car_data,pd.DataFrame(c_pred.reshape(len(c_pred),1),columns =['Price Prediction'])],axis =1))

model  year  price transmission  mileage fuelType  tax   mpg  \
0        A1  2017  12500       Manual    15735   Petrol  150  55.4   
1        A6  2016  16500    Automatic    36203   Diesel   20  64.2   
2        A1  2016  11000       Manual    29946   Petrol   30  55.4   
3        A4  2017  16800    Automatic    25952   Diesel  145  67.3   
4        A3  2019  17300       Manual     1998   Petrol  145  49.6   
...     ...   ...    ...          ...      ...      ...  ...   ...   
10663    A3  2020  16999       Manual     4018   Petrol  145  49.6   
10664    A3  2020  16999       Manual     1978   Petrol  150  49.6   
10665    A3  2020  17199       Manual      609   Petrol  150  49.6   
10666    Q3  2017  19499    Automatic     8646   Petrol  150  47.9   
10667    Q3  2016  15999       Manual    11855   Petrol  150  47.9   

       engineSize  Price Prediction  
0             1.4      14629.834824  
1             2.0      20670.907799  
2             1.4      13810.010320  
3             2.0      19949.798672  
4             1.0      17350.396723  
...           ...               ...  
10663         1.0      19190.495099  
10664         1.0      19277.571094  
10665         1.0      19407.661345  
10666         1.4      21034.831160  
10667         1.4      16691.093139  

[10668 rows x 10 columns]

## Display-Accuracy and Mean Absolute Error

In [76]:
from sklearn.metrics import r2_score,mean_absolute_error
print('Accuracy: ',r2_score(y,c_pred))
print('Mean_Absolute_Error: ',mean_absolute_error(y,c_pred))

Accuracy:  0.7907228785075128
Mean_Absolute_Error:  3344.6148563131032


## Create Model Extra Tree Regressor 

In [77]:
from sklearn.ensemble import  ExtraTreesRegressor
ET=ExtraTreesRegressor(n_estimators = 120)
ET.fit(x_train,y_train)
y_pred=ET.predict(x_test)
from sklearn.metrics import r2_score,mean_absolute_error
print  ('Accuracy: ', r2_score(y_test, y_pred))
print  ('Mean_Absolute_Error: ', mean_absolute_error(y_test,y_pred))

Accuracy:  0.9578188965822916
Mean_Absolute_Error:  1533.3951800218683


## Display the Result for Complete Dataset

In [78]:
c_pred = ET.predict(x)
display (c_pred)
result = pd.concat([car_data,pd.DataFrame(c_pred,columns = ['Price Prediction'])],axis=1)
display( result)

array([12500.   , 16500.   , 11000.   , ..., 17199.   , 19499.   ,
       18205.125])

model  year  price transmission  mileage fuelType  tax   mpg  \
0        A1  2017  12500       Manual    15735   Petrol  150  55.4   
1        A6  2016  16500    Automatic    36203   Diesel   20  64.2   
2        A1  2016  11000       Manual    29946   Petrol   30  55.4   
3        A4  2017  16800    Automatic    25952   Diesel  145  67.3   
4        A3  2019  17300       Manual     1998   Petrol  145  49.6   
...     ...   ...    ...          ...      ...      ...  ...   ...   
10663    A3  2020  16999       Manual     4018   Petrol  145  49.6   
10664    A3  2020  16999       Manual     1978   Petrol  150  49.6   
10665    A3  2020  17199       Manual      609   Petrol  150  49.6   
10666    Q3  2017  19499    Automatic     8646   Petrol  150  47.9   
10667    Q3  2016  15999       Manual    11855   Petrol  150  47.9   

       engineSize  Price Prediction  
0             1.4         12500.000  
1             2.0         16500.000  
2             1.4         11000.000  
3             2.0         16800.000  
4             1.0         17300.000  
...           ...               ...  
10663         1.0         16999.000  
10664         1.0         16999.000  
10665         1.0         17199.000  
10666         1.4         19499.000  
10667         1.4         18205.125  

[10668 rows x 10 columns]

## Display – Accuracy and Mean Absolute Error 

In [79]:
from sklearn.metrics import r2_score,mean_absolute_error
print  ('Accuracy: ', r2_score(y, c_pred))
print  ('Mean_Absolute_Error', mean_absolute_error(y,c_pred))

Accuracy:  0.9906480127089488
Mean_Absolute_Error 349.5338314741908


## RandomizedSearchCV

In [80]:
# Hyperparameter Tuning and RandomizedSearchCV - Model used – RandomForestRegressor
from sklearn.model_selection import RandomizedSearchCV
n_estimators = [int(x) for x in np.linspace(start = 80, stop = 1500, num = 10)]
max_features = ['auto', 'sqrt']
max_depth = [int(x) for x in np.linspace(6, 45, num = 5)]
min_samples_split = [2, 5, 10, 15, 100]
min_samples_leaf = [1, 2, 5, 10]

## create random grid

In [81]:
from sklearn.ensemble import RandomForestRegressor
rand_grid={'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf}

rf=RandomForestRegressor()

rCV=RandomizedSearchCV(estimator=rf,param_distributions=rand_grid,scoring='neg_mean_squared_error',n_iter=10,cv=5,random_state=42, n_jobs = -1)

## Fit Model

In [82]:
display(rCV.fit(x_train,y_train))

RandomizedSearchCV(cv=5, estimator=RandomForestRegressor(), n_jobs=-1,
                   param_distributions={'max_depth': [6, 15, 25, 35, 45],
                                        'max_features': ['auto', 'sqrt'],
                                        'min_samples_leaf': [1, 2, 5, 10],
                                        'min_samples_split': [2, 5, 10, 15,
                                                              100],
                                        'n_estimators': [80, 237, 395, 553, 711,
                                                         868, 1026, 1184, 1342,
                                                         1500]},
                   random_state=42, scoring='neg_mean_squared_error')

## Prediction for test data

In [83]:
rf_pred=rCV.predict(x_test)
display (rf_pred)

array([14105.02865017, 23660.41231408, 28513.04005731, ...,
       48237.29610101, 31291.37418711, 10015.96560576])

## Display Mean Absolute Error and Mean Squared Error

In [84]:
from sklearn.metrics import mean_absolute_error,mean_squared_error
print('MAE: ',mean_absolute_error(y_test,rf_pred))
print('MSE: ',mean_squared_error(y_test,rf_pred))

MAE:  1502.9087162052797
MSE:  5619248.988365508


## Display the Accuracy

In [85]:
from sklearn.metrics import r2_score
print('Accuracy: ',r2_score(y_test,rf_pred))

Accuracy:  0.9591077568189572


## Display the Result Complete the Data 

In [86]:
full_rf_pred=rCV.predict(x)
display (full_rf_pred)

array([13296.9181554 , 16581.95072185, 12002.25948257, ...,
       18088.48778862, 20496.81127637, 18501.29955784])

## Display Error and accuracy 

In [87]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
print('MAE: ',mean_absolute_error(y,full_rf_pred))
print('MSE: ',mean_squared_error(y,full_rf_pred))
print('Accuracy: ',r2_score(y,full_rf_pred))

MAE:  1136.5366659186463
MSE:  3154074.2243371014
Accuracy:  0.9770152513778261


# Create Random Forest Model Again

In [90]:
from sklearn.ensemble import RandomForestRegressor
rf=RandomForestRegressor()
rf.fit(x_train,y_train)
display(rf)

RandomForestRegressor()

## Create Pickle File 

In [91]:
#Use pickle and scaler to save our model so that we can use it later
import pickle

# Save the trained model
with open("random_forest.pkl", "wb") as f:
    pickle.dump(rf, f)

# Save the scaler
with open("random_scaler.pkl", "wb") as f:
    pickle.dump(sc, f)


## Load Pickle File and  do Prediction  

In [92]:
model=pickle.load(open('random_forest.pkl','rb'))
p_pred = model.predict (x)
print (p_pred)

[12849.35 16702.91 11603.73 ... 17749.04 20039.83 18647.81]


## Display the result   

In [93]:
result = pd.concat([car_data,pd.DataFrame(p_pred ,columns = ['Price Prediction'])],axis=1)
display( result)

model  year  price transmission  mileage fuelType  tax   mpg  \
0        A1  2017  12500       Manual    15735   Petrol  150  55.4   
1        A6  2016  16500    Automatic    36203   Diesel   20  64.2   
2        A1  2016  11000       Manual    29946   Petrol   30  55.4   
3        A4  2017  16800    Automatic    25952   Diesel  145  67.3   
4        A3  2019  17300       Manual     1998   Petrol  145  49.6   
...     ...   ...    ...          ...      ...      ...  ...   ...   
10663    A3  2020  16999       Manual     4018   Petrol  145  49.6   
10664    A3  2020  16999       Manual     1978   Petrol  150  49.6   
10665    A3  2020  17199       Manual      609   Petrol  150  49.6   
10666    Q3  2017  19499    Automatic     8646   Petrol  150  47.9   
10667    Q3  2016  15999       Manual    11855   Petrol  150  47.9   

       engineSize  Price Prediction  
0             1.4          12849.35  
1             2.0          16702.91  
2             1.4          11603.73  
3             2.0          17579.03  
4             1.0          17417.27  
...           ...               ...  
10663         1.0          16922.19  
10664         1.0          17066.25  
10665         1.0          17749.04  
10666         1.4          20039.83  
10667         1.4          18647.81  

[10668 rows x 10 columns]

## Display the Accuracy and Error   

In [94]:
from sklearn.metrics import r2_score,mean_absolute_error
print  ('Accuracy: ', r2_score(y, p_pred))
print  ('Mean_Absolute_Error: ', mean_absolute_error(y,p_pred))

Accuracy:  0.986070203177762
Mean_Absolute_Error:  784.2643814245056
